#!/usr/bin/env python3
"""Emit BMAD epics.md and per-story files. Run from repo root."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PLAN = ROOT / "_bmad-output" / "planning-artifacts"
IMPL = ROOT / "_bmad-output" / "implementation-artifacts"

VERIFY_BASE = [
    "python3 tooling/planning-checks.py",
    "npx --yes markdownlint-cli2 'docs/**/*.md' README.md AGENTS.md",
]

HUMAN = "blocked-human-validation: never fabricate VoiceOver, Voice Control, Switch Control, TCC, signed capture, notarization, or linguistic QA evidence."


def gwt(given: str, when: str, then: str, extra: list[str] | None = None) -> str:
    lines = [
        f"**Given** {given}",
        f"**When** {when}",
        f"**Then** {then}",
    ]
    for item in extra or []:
        lines.append(f"**And** {item}")
    return "\n".join(lines)


def story_md(
    title: str,
    role: str,
    want: str,
    so: str,
    reqs: str,
    adrs: str,
    deps: str,
    ac: str,
    fail: str,
    cross: str,
    verify: list[str],
    evidence: str,
    nongoals: str,
    human: bool = False,
) -> str:
    cmds = "\n".join(f"- `{c}`" for c in verify)
    gate = f"\n\n**Human gate:** {HUMAN}" if human else ""
    return f"""As a {role},
I want {want},
So that {so}.

**Requirements:** {reqs}
**ADRs:** {adrs}
**Dependencies:** {deps}
**Blocking gates:** {"human-only evidence; DG as named" if human else "none beyond listed dependencies; Proposed ADR-002/009/018 remain unresolved"}

**Acceptance Criteria:**

{ac}

**Failure / recovery:**
{fail}

**Security / privacy / diagnostics / a11y / i18n / data:**
{cross}

**Automated verification:**
{cmds}

**Signed-build / manual evidence:**
{evidence}

**Non-goals:**
{nongoals}{gate}
"""


EPICS: list[dict] = [
    {
        "n": 1,
        "title": "Bootable toolchain and empty app",
        "goal": "A developer can clone the branch and run format/lint/type/unit gates on an empty macOS Tauri workspace with no product behavior and no network.",
        "stories": [
            {
                "m": 1,
                "title": "Pin toolchain manifests",
                "role": "developer",
                "want": "pinned Node, pnpm, Rust, and Swift identity files",
                "so": "later stories share one bootstrap",
                "reqs": "G-01 (process), SEC-005 (reproducible later)",
                "adrs": "ADR-003; ADR-002 remains Proposed",
                "deps": "none (canary)",
                "ac": gwt(
                    "a clean `bmad/bronze-autonomous` tree",
                    "toolchain pin files are added",
                    "`package.json` packageManager, Node engines, `rust-toolchain.toml` matching docs/20, and Swift tools version notes exist",
                    ["no application windows, capture, or SQLite yet", "docs/20 versions remain the recorded host baseline"],
                ),
                "fail": "If a pin disagrees with docs/20, fail the story and update the pin or the bootstrap record — do not silently raise macOS deployment target (ADR-002).",
                "cross": "No secrets in pin files. No telemetry SDK. No user-facing strings.",
                "verify": VERIFY_BASE + ["test -f package.json", "test -f rust-toolchain.toml"],
                "evidence": "file existence only; no signed app",
                "nongoals": "Tauri window, UI, native capture, CI cloud, Intel universal2",
            },
            {
                "m": 2,
                "title": "Scaffold pnpm Turbo workspace",
                "role": "developer",
                "want": "pnpm-workspace and Turbo with empty packages",
                "so": "JS work has a graph before product code",
                "reqs": "SEC-001, I18N-001 (package slots)",
                "adrs": "ADR-003, ADR-017",
                "deps": "Story 1.1",
                "ac": gwt(
                    "pinned package manager",
                    "workspace is scaffolded",
                    "`pnpm-workspace.yaml`, `turbo.json`, `packages/ui`, `packages/contracts`, `packages/i18n`, `packages/test-support`, `apps/desktop` exist",
                    ["no product features", "Turbo cache disabled is not required yet because no signing tasks exist"],
                ),
                "fail": "If pnpm install needs network, use lockfile creation once then keep lockfile; do not add remote fonts or CDN.",
                "cross": "packages/ui must not own product state. No raw user strings in TSX.",
                "verify": VERIFY_BASE + ["pnpm install", "pnpm exec turbo run lint --force || true"],
                "evidence": "local install log",
                "nongoals": "shadcn components, Tauri commands, capture",
            },
            {
                "m": 3,
                "title": "Scaffold Cargo workspace",
                "role": "developer",
                "want": "Cargo workspace crates with rustfmt and Clippy deny-warnings",
                "so": "Rust domain has a home",
                "reqs": "DAT-001 (slot), SEC-002 (slot)",
                "adrs": "ADR-003, ADR-008, ADR-010",
                "deps": "Story 1.1",
                "ac": gwt(
                    "toolchain pin",
                    "crates are created",
                    "`bronze-domain`, `bronze-capture`, `bronze-storage`, `bronze-settings`, `bronze-diagnostics`, `bronze-platform`, `bronze-platform-macos` compile empty",
                    ["Clippy `-D warnings` on workspace", "no SQL, AX, or Tauri commands yet"],
                ),
                "fail": "Compilation failure blocks. Do not allow unused-mut warnings.",
                "cross": "No macOS framework imports outside bronze-platform-macos.",
                "verify": ["cargo fmt --check", "cargo clippy --workspace -- -D warnings", "cargo test --workspace"],
                "evidence": "local cargo logs",
                "nongoals": "schema, ABI, event tap",
            },
            {
                "m": 4,
                "title": "Scaffold Swift package",
                "role": "developer",
                "want": "BronzeNative Swift package skeleton",
                "so": "native work has a package before ABI",
                "reqs": "CAP-001 (slot)",
                "adrs": "ADR-004",
                "deps": "Story 1.1",
                "ac": gwt(
                    "Xcode present",
                    "Package.swift is added under native/macos/BronzeNative",
                    "package builds a static library with ABI version placeholder",
                    ["no event tap, AX, or AppKit window code yet"],
                ),
                "fail": "If SwiftPM cannot build, stop; do not embed source in Tauri without a package.",
                "cross": "No logging of strings. No JS surface.",
                "verify": ["swift build --package-path native/macos/BronzeNative"],
                "evidence": "local swift build",
                "nongoals": "CGEventTap, AX, status item",
            },
            {
                "m": 5,
                "title": "Empty Tauri app with CSP deny",
                "role": "developer",
                "want": "a Tauri 2 macOS app that loads packaged UI with default-deny capabilities",
                "so": "security baseline exists before features",
                "reqs": "SEC-001, SEC-002, SEC-003, SEC-004",
                "adrs": "ADR-003, ADR-010, ADR-017",
                "deps": "Stories 1.2 and 1.3",
                "ac": gwt(
                    "JS and Cargo workspaces",
                    "Tauri app is created",
                    "production CSP has no remote origins, no eval, no frames",
                    [
                        "capabilities exist for quick, library, settings, onboarding and grant no shell/fs/http/sql",
                        "DevTools disabled in release config",
                        "forbidden-command test from a fixture window fails closed",
                    ],
                ),
                "fail": "Any allowed shell/fs/http plugin is S0; remove it.",
                "cross": "Zero runtime network in default build. No arbitrary path from WebView.",
                "verify": ["pnpm exec tauri build --debug --no-bundle || cargo test -p bronze-desktop -- --nocapture", "rg -n 'shell|http|sql' apps/desktop/src-tauri/capabilities || true"],
                "evidence": "capability JSON review; not notarized",
                "nongoals": "capture, queue UI, signing identity",
            },
            {
                "m": 6,
                "title": "i18n catalogs and pseudo-locales",
                "role": "developer",
                "want": "en, en-XA, ar-XB catalogs and missing-key CI",
                "so": "later UI cannot hard-code copy",
                "reqs": "I18N-001, I18N-002, I18N-003, G-06",
                "adrs": "ADR-014",
                "deps": "Story 1.2",
                "ac": gwt(
                    "packages/i18n exists",
                    "catalogs and validators are added",
                    "build fails on missing keys or placeholder mismatch",
                    ["script-preserving fallback unit tests include zh-Hant-HK → zh-Hant → zh → en", "no user-facing English literals in new TSX"],
                ),
                "fail": "Concatenated sentences fail CI.",
                "cross": "User content never enters catalogs. ICU plurals required for counts.",
                "verify": ["pnpm --filter @bronze/i18n test", "pnpm --filter @bronze/i18n validate"],
                "evidence": "unit tests only; no linguistic QA",
                "nongoals": "human translation, native InfoPlist strings (later story)",
            },
            {
                "m": 7,
                "title": "shadcn React Aria foundation",
                "role": "developer",
                "want": "owned shadcn components on React Aria with tokens and visible focus",
                "so": "UI stories do not mix primitive bases",
                "reqs": "A11Y-001, A11Y-002, A11Y-003",
                "adrs": "ADR-012, ADR-013",
                "deps": "Stories 1.2 and 1.6",
                "ac": gwt(
                    "packages/ui exists",
                    "shadcn init uses React Aria base",
                    "Button/TextField/Dialog primitives have role/name/focus tests",
                    ["no clickable div", "focus-visible not removed", "Reduce Motion / Increase Contrast CSS hooks exist"],
                ),
                "fail": "If React Aria base cannot initialize, stop for DG-06 rather than mixing Radix.",
                "cross": "axe on default/empty/focus states. No color-only status.",
                "verify": ["pnpm --filter @bronze/ui test", "pnpm --filter @bronze/ui lint"],
                "evidence": "component tests; not VoiceOver",
                "nongoals": "queue cards, virtualized lists, contenteditable",
            },
            {
                "m": 8,
                "title": "Workspace verify aggregate",
                "role": "developer",
                "want": "one local verify command covering format, lint, types, unit, i18n, planning-checks",
                "so": "later stories have a gate",
                "reqs": "G-01 process, SEC-001 config",
                "adrs": "ADR-003",
                "deps": "Stories 1.2–1.7",
                "ac": gwt(
                    "workspaces exist",
                    "root verify script is added",
                    "`pnpm verify` runs Biome/tsc/Vitest/i18n validate/cargo test/planning-checks",
                    ["signing/TCC tasks are not Turbo-cached", "verify fails if any required step fails"],
                ),
                "fail": "Do not weaken a failing check to go green.",
                "cross": "planning-checks remain required.",
                "verify": ["pnpm verify"],
                "evidence": "command output",
                "nongoals": "GitHub Actions beyond local script",
            },
        ],
    },
    {
        "n": 2,
        "title": "In-process Swift bridge",
        "goal": "Tauri executable links BronzeNative and completes ABI round trips without JS seeing Swift.",
        "stories": [
            {
                "m": 1,
                "title": "Versioned C ABI types",
                "role": "developer",
                "want": "fixed-width ABI version, tagged enums, pointer-plus-length UTF-8",
                "so": "Rust and Swift share one contract",
                "reqs": "CAP-004, SEC-002",
                "adrs": "ADR-004",
                "deps": "Story 1.4",
                "ac": gwt(
                    "BronzeNative package exists",
                    "ABI headers/module are added",
                    "version check fails closed on mismatch",
                    ["no NUL-terminated string reliance", "no unwind across boundary documented in tests"],
                ),
                "fail": "Invalid UTF-8 rejected. Double completion forbidden.",
                "cross": "Sensitive buffers have no debug description.",
                "verify": ["swift test --package-path native/macos/BronzeNative"],
                "evidence": "unit tests",
                "nongoals": "AX, event tap, pasteboard",
            },
            {
                "m": 2,
                "title": "Rust macOS façade",
                "role": "developer",
                "want": "bronze-platform-macos safe façade over the ABI",
                "so": "domain crates never call Swift directly",
                "reqs": "CAP-004",
                "adrs": "ADR-004",
                "deps": "Stories 1.3 and 2.1",
                "ac": gwt(
                    "ABI types exist",
                    "façade crate is implemented",
                    "init/shutdown and version query work",
                    ["bronze-domain has no macOS imports"],
                ),
                "fail": "Panic at FFI boundary is contained.",
                "cross": "No content logging.",
                "verify": ["cargo test -p bronze-platform-macos", "cargo clippy -p bronze-platform-macos -- -D warnings"],
                "evidence": "unit tests",
                "nongoals": "real AX queries",
            },
            {
                "m": 3,
                "title": "Link static library into Tauri",
                "role": "developer",
                "want": "the debug app links BronzeNative in-process",
                "so": "one TCC subject exists",
                "reqs": "SEC-005 (identity later), CAP-001 slot",
                "adrs": "ADR-004, ADR-011",
                "deps": "Stories 1.5 and 2.2",
                "ac": gwt(
                    "façade and Tauri app exist",
                    "the app is built",
                    "release-like bundle contains no helper executable",
                    ["startup calls ABI version check"],
                ),
                "fail": "Link failure blocks; do not switch to a sidecar.",
                "cross": "One process identity.",
                "verify": ["cargo test -p bronze-desktop", "swift build --package-path native/macos/BronzeNative"],
                "evidence": "local debug build; not Developer ID",
                "nongoals": "notarization, App Group",
            },
            {
                "m": 4,
                "title": "ABI ownership tests",
                "role": "developer",
                "want": "empty, embedded NUL, invalid UTF-8, large payload, cancel, shutdown-race tests",
                "so": "bridge memory is proven before capture",
                "reqs": "CAP-004, SEC-006",
                "adrs": "ADR-004, ADR-015",
                "deps": "Story 2.3",
                "ac": gwt(
                    "linked app",
                    "ABI conformance suite runs",
                    "each case completes exactly once or cancels",
                    ["10k round-trip smoke optional if runtime allows; otherwise document follow-up"],
                ),
                "fail": "Leak or double-free fails the story.",
                "cross": "No content in diagnostics.",
                "verify": ["swift test --package-path native/macos/BronzeNative", "cargo test -p bronze-platform-macos"],
                "evidence": "tests; sanitizers when compatible",
                "nongoals": "capture matrix",
            },
        ],
    },
    {
        "n": 3,
        "title": "Capture coordinator and AX-first selection",
        "goal": "Every observed trigger gets an ID and one terminal outcome; AX is primary; synthetic clipboard stays off.",
        "stories": [
            {
                "m": 1,
                "title": "Permission snapshot enum",
                "role": "developer",
                "want": "closed permission states without prompting",
                "so": "health UI later has a typed model",
                "reqs": "SET-003, SET-004, CAP-010",
                "adrs": "ADR-005, ADR-015",
                "deps": "Story 1.3",
                "ac": gwt(
                    "crates exist",
                    "permission enum is implemented",
                    "values are unknown|not_requested|denied|granted_unverified|healthy|degraded|unavailable|requires_relaunch",
                    ["preflight APIs are wrapped but not called to prompt", "granted is not treated as healthy"],
                ),
                "fail": "Unknown platform result maps to unknown/degraded, never healthy.",
                "cross": "No key/content in snapshots.",
                "verify": ["cargo test -p bronze-settings permission", "cargo test -p bronze-platform-macos permission"],
                "evidence": "unit tests; not TCC UI",
                "nongoals": "System Settings deep link UI",
            },
            {
                "m": 2,
                "title": "Double-tap FSM tests",
                "role": "developer",
                "want": "pure modifier FSM with property tests",
                "so": "gesture logic is proven without the tap",
                "reqs": "CAP-002, A11Y-001",
                "adrs": "ADR-005",
                "deps": "Story 1.4",
                "ac": gwt(
                    "Swift package exists",
                    "FSM is implemented with table/property tests",
                    "valid pair emits one trigger; invalid sequences emit zero",
                    ["disabled by default", "timing window allows ≥500 ms", "no key stream retained"],
                ),
                "fail": "Stuck state or wall-clock dependence fails.",
                "cross": "Non-timed routes remain required. No character logging.",
                "verify": ["swift test --package-path native/macos/BronzeNative --filter FSM"],
                "evidence": "unit tests; not 1000 physical trials",
                "nongoals": "live CGEventTap",
            },
            {
                "m": 3,
                "title": "Listen-only event tap thread",
                "role": "developer",
                "want": "session listenOnly tap on a dedicated run-loop thread",
                "so": "optional gesture can be enabled later",
                "reqs": "CAP-002, CAP-004",
                "adrs": "ADR-004, ADR-005",
                "deps": "Stories 2.3 and 3.2",
                "ac": gwt(
                    "FSM exists",
                    "tap thread is implemented",
                    "callback does no AX, DB, window, clipboard, or log work",
                    ["SPSC is single-producer", "tap disable resets FSM"],
                ),
                "fail": "If Input Monitoring is denied, degrade; keep chord/menu routes (even if unimplemented UI).",
                "cross": "Never suppress events. No keycodes persisted.",
                "verify": ["swift test --package-path native/macos/BronzeNative --filter EventTap"],
                "evidence": "unit/fake tests; physical 1k trials are human",
                "nongoals": "prompting TCC",
            },
            {
                "m": 4,
                "title": "Atomic ingress snapshot",
                "role": "developer",
                "want": "CaptureIngressContext seqlock snapshot",
                "so": "queued work cannot retarget",
                "reqs": "CAP-004, CAP-008, CAP-009, QUE-001",
                "adrs": "ADR-005, ADR-006",
                "deps": "Stories 2.2 and 3.3",
                "ac": gwt(
                    "native façade exists",
                    "ingress context is implemented",
                    "snapshot includes target PID, bundle token, activation generation, destination UUID, accept-capture generation, policy/settings revisions, route, monotonic time",
                    ["inconsistent read returns context_unavailable", "focused element is not in event-tap snapshot"],
                ),
                "fail": "Never substitute current frontmost app.",
                "cross": "No titles/URLs in ingress.",
                "verify": ["cargo test -p bronze-capture ingress", "swift test --package-path native/macos/BronzeNative --filter Ingress"],
                "evidence": "unit tests",
                "nongoals": "real AX focus identity (next stories)",
            },
            {
                "m": 5,
                "title": "Serial capture coordinator",
                "role": "developer",
                "want": "monotonic request IDs and exactly one terminal outcome",
                "so": "no silent drops",
                "reqs": "CAP-004, G-01, G-02",
                "adrs": "ADR-006, ADR-015",
                "deps": "Story 3.4",
                "ac": gwt(
                    "ingress exists",
                    "coordinator is implemented",
                    "20 synthetic triggers preserve order and all terminate",
                    ["overflow emits trigger_queue_overflow per missing ID", "success feedback cannot fire before persist hook"],
                ),
                "fail": "Nonterminal request fails the suite.",
                "cross": "Diagnostics independent of content transaction.",
                "verify": ["cargo test -p bronze-capture coordinator"],
                "evidence": "unit/property tests",
                "nongoals": "real AX",
            },
            {
                "m": 6,
                "title": "AX provider with fakes",
                "role": "developer",
                "want": "AX-first provider using fixtures",
                "so": "secure fields never leak",
                "reqs": "CAP-005, CAP-006, CAP-007, CAP-009",
                "adrs": "ADR-006",
                "deps": "Story 3.5",
                "ac": gwt(
                    "coordinator exists",
                    "AX provider is implemented against fakes",
                    "secure/unknown protection fail closed with zero content in ABI/log/store",
                    ["whitespace preserved", "exclusion runs before content query", "empty/zero-width is no_selection without trim"],
                ),
                "fail": "Any content on protected_content is S0.",
                "cross": "Diagnostics have no text/title/URL/hash of secrets.",
                "verify": ["cargo test -p bronze-capture ax", "swift test --package-path native/macos/BronzeNative --filter AX"],
                "evidence": "fixtures; not real Safari/Chrome matrix",
                "nongoals": "synthetic Cmd-C",
            },
            {
                "m": 7,
                "title": "Manual clipboard import",
                "role": "developer",
                "want": "explicit Create from Clipboard",
                "so": "users can capture without AX",
                "reqs": "CAP-003, CAP-005",
                "adrs": "ADR-006",
                "deps": "Story 3.5",
                "ac": gwt(
                    "coordinator exists",
                    "manual clipboard command is added",
                    "it reads text only after explicit action",
                    ["synthetic fallback remains off", "stale generation fails clipboard_changed"],
                ),
                "fail": "Do not restore clipboard. Do not ingest files/images.",
                "cross": "Shared pasteboard disclosure not required for manual path beyond help later.",
                "verify": ["cargo test -p bronze-capture clipboard_manual"],
                "evidence": "unit tests",
                "nongoals": "synthetic Cmd-C enablement",
            },
            {
                "m": 8,
                "title": "Content-free diagnostic schema",
                "role": "developer",
                "want": "typed diagnostic_events without content fields",
                "so": "CAP-010 is structurally true",
                "reqs": "CAP-010, SEC-006, SUP-002",
                "adrs": "ADR-015",
                "deps": "Stories 1.3 and 3.5",
                "ac": gwt(
                    "diagnostics crate exists",
                    "schema is implemented",
                    "type system rejects String payloads for selected text",
                    ["seeded secret scan of logs passes", "diagnostic write failure does not roll back a saved item fake"],
                ),
                "fail": "Content type in schema is S0.",
                "cross": "Support bundle preview comes in a later epic.",
                "verify": ["cargo test -p bronze-diagnostics"],
                "evidence": "type/unit tests",
                "nongoals": "export UI",
            },
            {
                "m": 9,
                "title": "TCC grant deny revoke evidence",
                "role": "operator",
                "want": "signed-build TCC matrix recorded",
                "so": "permissions are not claimed from unit tests",
                "reqs": "SET-003, SET-004, CAP-001, CAP-002",
                "adrs": "ADR-005, ADR-011",
                "deps": "Stories 3.1–3.3",
                "ac": gwt(
                    "a signed local identity build exists",
                    "a human runs grant/deny/revoke/relaunch",
                    "results are recorded as blocked-human-validation until executed",
                    ["this story cannot be marked done by an agent without that evidence file"],
                ),
                "fail": "Do not fabricate.",
                "cross": "No content logs during tests.",
                "verify": ["test ! -f docs/evidence/tcc-matrix.md && echo pending"],
                "evidence": HUMAN,
                "nongoals": "agent-completed TCC",
                "human": True,
            },
            {
                "m": 10,
                "title": "Signed AX source matrix",
                "role": "operator",
                "want": "TextEdit/Safari/Chrome/editor/terminal/secure-field matrix",
                "so": "supported sources are evidence-backed",
                "reqs": "CAP-005, CAP-006, G-01, DG-03",
                "adrs": "ADR-006",
                "deps": "Story 3.6",
                "ac": gwt(
                    "AX provider exists",
                    "human runs the mandatory source matrix on a signed build",
                    "each row records provider path and limitation",
                    ["story stays blocked-human-validation until the matrix file exists"],
                ),
                "fail": "Do not count unknown apps toward 99.9%.",
                "cross": "Secure fixtures must show zero content.",
                "verify": ["test ! -f docs/evidence/ax-matrix.md && echo pending"],
                "evidence": HUMAN,
                "nongoals": "agent-claimed compatibility",
                "human": True,
            },
        ],
    },
    {
        "n": 4,
        "title": "Transactional store and portability",
        "goal": "SQLite WAL, migrations, undo, backup, and deterministic export without WebView SQL.",
        "stories": [
            {
                "m": 1,
                "title": "Domain entities and lifecycle",
                "role": "developer",
                "want": "section/item entities with closed lifecycle and content_language",
                "so": "UI cannot invent states",
                "reqs": "QUE-001, QUE-002, QUE-003, I18N-003, DAT-001",
                "adrs": "ADR-008, ADR-014",
                "deps": "Story 1.3",
                "ac": gwt(
                    "bronze-domain exists",
                    "entities are implemented",
                    "lifecycle is queued|copied|active|done|skipped|trashed with a transition table",
                    ["content_language is BCP 47 or und defaulting to und", "invalid transitions fail"],
                ),
                "fail": "Silent trim/normalize of body fails tests.",
                "cross": "UTC timestamps. Locale-neutral enums.",
                "verify": ["cargo test -p bronze-domain"],
                "evidence": "unit tests",
                "nongoals": "SQLite yet",
            },
            {
                "m": 2,
                "title": "Schema v1 and migrations",
                "role": "developer",
                "want": "versioned checksummed migrations and WAL",
                "so": "data survives upgrades",
                "reqs": "DAT-001, G-03",
                "adrs": "ADR-008; ADR-009 Proposed so locator is an interface",
                "deps": "Story 4.1",
                "ac": gwt(
                    "entities exist",
                    "schema v1 is applied",
                    "tables match docs/08 including command_receipts and diagnostic_events",
                    ["backup-before-migration hook exists even if backup story is next", "WebView has no SQL"],
                ),
                "fail": "Failed migration keeps original DB and enters read-only.",
                "cross": "0600/0700 modes where possible. No iCloud default path.",
                "verify": ["cargo test -p bronze-storage migrate"],
                "evidence": "migration fixtures",
                "nongoals": "App Group container decision",
            },
            {
                "m": 3,
                "title": "Command receipts and revisions",
                "role": "developer",
                "want": "idempotent command IDs and optimistic revisions",
                "so": "retries do not duplicate work",
                "reqs": "DAT-001, QUE-002",
                "adrs": "ADR-008",
                "deps": "Story 4.2",
                "ac": gwt(
                    "schema exists",
                    "command API is implemented",
                    "duplicate ID inside window reconstructs prior result",
                    ["expired ID returns idempotency_expired and does not execute", "receipts contain no body"],
                ),
                "fail": "Stale revision returns typed conflict.",
                "cross": "Content-free receipts.",
                "verify": ["cargo test -p bronze-storage receipts"],
                "evidence": "unit tests",
                "nongoals": "UI conflict dialog",
            },
            {
                "m": 4,
                "title": "Undo trash and purge",
                "role": "developer",
                "want": "tombstones, undo inverses, dependency-safe purge",
                "so": "deletes are recoverable",
                "reqs": "QUE-006, DAT-004",
                "adrs": "ADR-008",
                "deps": "Story 4.3",
                "ac": gwt(
                    "items persist",
                    "trash/undo/purge are implemented",
                    "purge never cascade-deletes non-trashed descendants",
                    ["default trash 30 days", "forensic erasure is not claimed"],
                ),
                "fail": "Empty Trash without confirmation API is forbidden.",
                "cross": "FTS rows removed on purge when FTS exists.",
                "verify": ["cargo test -p bronze-storage undo", "cargo test -p bronze-domain purge"],
                "evidence": "unit tests",
                "nongoals": "Empty Trash UI",
            },
            {
                "m": 5,
                "title": "Online backup restore",
                "role": "developer",
                "want": "SQLite online backup API and verified restore",
                "so": "DAT-002 holds",
                "reqs": "DAT-002",
                "adrs": "ADR-008",
                "deps": "Story 4.2",
                "ac": gwt(
                    "schema exists",
                    "backup/restore are implemented",
                    "schedule enum is daily|weekly only",
                    ["restore snapshots current DB first", "integrity failure does not swap"],
                ),
                "fail": "File-copy of live WAL is forbidden.",
                "cross": "Backups inherit 0600. No network.",
                "verify": ["cargo test -p bronze-storage backup"],
                "evidence": "fault tests",
                "nongoals": "backup UI",
            },
            {
                "m": 6,
                "title": "Deterministic export import",
                "role": "developer",
                "want": "JSON archive plus Markdown with contentLanguage",
                "so": "users can leave",
                "reqs": "DAT-003, SET-001, I18N-003",
                "adrs": "ADR-008, ADR-014",
                "deps": "Stories 4.2 and 4.1",
                "ac": gwt(
                    "items persist",
                    "export/import run",
                    "manifest is locale-neutral and sorted",
                    ["preview warns that item bodies may contain secrets", "path traversal archives fail", "settings export excludes diagnostics/paths/tokens"],
                ),
                "fail": "Silent overwrite forbidden.",
                "cross": "No machine paths. Hostile corpus required.",
                "verify": ["cargo test -p bronze-storage export"],
                "evidence": "golden/fuzz tests",
                "nongoals": "file picker UI",
            },
            {
                "m": 7,
                "title": "Search placeholder pending ADR-018",
                "role": "developer",
                "want": "FTS hook that does not claim locale semantics",
                "so": "QUE-007 is not falsely completed",
                "reqs": "QUE-007, G-06, DG-10",
                "adrs": "ADR-018 Proposed",
                "deps": "Story 4.2",
                "ac": gwt(
                    "items persist",
                    "a naive FTS or application filter exists",
                    "story documents ADR-018 as blocking complete locale search",
                    ["raw body unchanged", "query never enters diagnostics"],
                ),
                "fail": "Do not mark QUE-007 done.",
                "cross": "FTS is sensitive data.",
                "verify": ["cargo test -p bronze-storage search_placeholder"],
                "evidence": "unit tests; tokenizer gate open",
                "nongoals": "final tokenizer",
            },
        ],
    },
    {
        "n": 5,
        "title": "Native shell and accessible feedback",
        "goal": "Status menu, activating panel, focus restore, and native display-preference bridge.",
        "stories": [
            {
                "m": 1,
                "title": "Status item and menu",
                "role": "user",
                "want": "an accessible status menu with Capture, New Note, Show, Settings, Quit",
                "so": "I can work without a global hook",
                "reqs": "CAP-003, WIN-004, A11Y-001, I18N-001",
                "adrs": "ADR-007, ADR-014",
                "deps": "Stories 1.5, 1.6, 2.3",
                "ac": gwt(
                    "empty Tauri app",
                    "status item is added",
                    "menu items have localized accessible names",
                    ["Capture uses last-external-target snapshot contract even if capture is stubbed", "menu works when event tap is off"],
                ),
                "fail": "Missing accessible name fails.",
                "cross": "Native strings from same catalog ownership.",
                "verify": ["cargo test -p bronze-platform-macos status_item", "pnpm verify"],
                "evidence": "unit; VoiceOver is human",
                "nongoals": "real capture success",
            },
            {
                "m": 2,
                "title": "Quick panel window and physical edge",
                "role": "user",
                "want": "to summon a key-capable panel on a physical left/right/top edge",
                "so": "I can see the queue",
                "reqs": "WIN-001, WIN-002, WIN-005",
                "adrs": "ADR-007",
                "deps": "Stories 1.5 and 5.1",
                "ac": gwt(
                    "Tauri windows exist",
                    "quick panel is implemented",
                    "stored edge is physical not RTL-leading",
                    ["work area clamping exists", "panel is activating", "no focus trap"],
                ),
                "fail": "Nonactivating NSPanel is forbidden.",
                "cross": "RTL does not mirror stored edge.",
                "verify": ["cargo test -p bronze-desktop window_edge", "pnpm --filter desktop test"],
                "evidence": "unit; multi-display matrix is human",
                "nongoals": "full queue CRUD",
            },
            {
                "m": 3,
                "title": "Focus restore and capture-only silence",
                "role": "user",
                "want": "capture-only success to keep source focus",
                "so": "I am not yanked into Bronze",
                "reqs": "WIN-003, CAP-004, A11Y-006",
                "adrs": "ADR-007",
                "deps": "Stories 3.5 and 5.2",
                "ac": gwt(
                    "panel and coordinator exist",
                    "focus policy is implemented",
                    "capture-only does not steal source focus",
                    ["native announcement API is called for hidden WebView case (can be tested with fake)", "Escape restores prior focus where safe"],
                ),
                "fail": "Hidden WKWebView live region is not accepted as the only feedback.",
                "cross": "Announcement text localized.",
                "verify": ["cargo test -p bronze-capture focus_policy", "pnpm --filter desktop test"],
                "evidence": "unit/fake; VoiceOver human",
                "nongoals": "VoiceOver sign-off",
            },
            {
                "m": 4,
                "title": "Native display preference bridge",
                "role": "user",
                "want": "Reduce Motion, Reduce Transparency, Increase Contrast, Differentiate Without Color applied live",
                "so": "OS preferences are honored",
                "reqs": "A11Y-003, WIN-004",
                "adrs": "ADR-012, ADR-013",
                "deps": "Stories 1.7 and 2.3",
                "ac": gwt(
                    "native façade exists",
                    "NSWorkspace display options are read and observed",
                    "one typed snapshot is published to WebViews",
                    ["app overrides only strengthen", "tokens update without restart"],
                ),
                "fail": "Weakening system Reduce Motion is forbidden.",
                "cross": "No color-only status.",
                "verify": ["cargo test -p bronze-platform-macos display_prefs", "pnpm --filter @bronze/ui test"],
                "evidence": "unit; manual OS toggle is human",
                "nongoals": "full AT matrix",
            },
            {
                "m": 5,
                "title": "Spaces and display matrix",
                "role": "operator",
                "want": "manual Spaces/full-screen/multi-display evidence",
                "so": "WIN-002 is not claimed from unit tests",
                "reqs": "WIN-001, WIN-002, DG-05",
                "adrs": "ADR-007",
                "deps": "Story 5.2",
                "ac": gwt(
                    "panel exists",
                    "human runs display matrix",
                    "story remains blocked-human-validation until evidence exists",
                    [],
                ),
                "fail": "Do not fabricate.",
                "cross": "n/a",
                "verify": ["test ! -f docs/evidence/display-matrix.md && echo pending"],
                "evidence": HUMAN,
                "nongoals": "agent-done display matrix",
                "human": True,
            },
        ],
    },
    {
        "n": 6,
        "title": "Queue and library UI",
        "goal": "Users can add, order, copy, complete, and search items from semantic UI.",
        "stories": [
            {
                "m": 1,
                "title": "Composer add item",
                "role": "user",
                "want": "to add a multiline note with Cmd-Enter",
                "so": "I can park a prompt",
                "reqs": "QUE-002, CAP-003, I18N-003, A11Y-002",
                "adrs": "ADR-012, ADR-014",
                "deps": "Stories 1.7, 4.3, 5.2",
                "ac": gwt(
                    "panel and store exist",
                    "composer is implemented",
                    "Cmd-Enter adds; Enter during isComposing does not",
                    ["failure retains draft", "content_language defaults to und", "strings from catalog"],
                ),
                "fail": "Clearing composer before persist is forbidden.",
                "cross": "IME-safe. Role/name tests. axe on empty/error.",
                "verify": ["pnpm --filter desktop test -- composer", "pnpm verify"],
                "evidence": "component tests; IME human later",
                "nongoals": "Markdown preview fetch",
            },
            {
                "m": 2,
                "title": "Item list lifecycle and menus",
                "role": "user",
                "want": "to edit, complete, skip, and trash items from buttons/menus",
                "so": "the queue is usable without drag",
                "reqs": "QUE-002, QUE-003, QUE-006, A11Y-002, A11Y-004, A11Y-006",
                "adrs": "ADR-012",
                "deps": "Story 6.1",
                "ac": gwt(
                    "items exist",
                    "cards use semantic list/article and real buttons",
                    "Move Up/Down exist; drag is optional",
                    ["accessible name contains visible label", "keyboard operates all actions"],
                ),
                "fail": "Clickable div fails the story.",
                "cross": "200% text still usable. No hover-only actions.",
                "verify": ["pnpm --filter desktop test -- queue", "pnpm --filter desktop test -- a11y"],
                "evidence": "axe/keyboard tests",
                "nongoals": "VoiceOver sign-off",
            },
            {
                "m": 3,
                "title": "Sections and library window",
                "role": "user",
                "want": "active section in the panel and a library window for archive/trash/search",
                "so": "capabilities stay least-privilege",
                "reqs": "QUE-001, QUE-008, WIN-005, SEC-002",
                "adrs": "ADR-010, ADR-007",
                "deps": "Stories 5.2 and 6.2",
                "ac": gwt(
                    "queue UI exists",
                    "library window is added",
                    "quick cannot import/export/backup",
                    ["library can paginate and archive", "empty/loading/read-only states exist"],
                ),
                "fail": "Capability leak is S0.",
                "cross": "Per-window commands tested negative.",
                "verify": ["cargo test -p bronze-desktop capabilities", "pnpm --filter desktop test -- library"],
                "evidence": "IPC denial tests",
                "nongoals": "import UI (epic 7)",
            },
            {
                "m": 4,
                "title": "Output profiles and copy",
                "role": "user",
                "want": "to copy items with a named profile",
                "so": "pasteboard output is deterministic",
                "reqs": "QUE-004, QUE-005",
                "adrs": "ADR-008",
                "deps": "Stories 4.3 and 6.2",
                "ac": gwt(
                    "items exist",
                    "copy command runs",
                    "profile is sole postCopyAction/advancePolicy authority",
                    ["lifecycle changes only after pasteboard success", "default copied+keep", "no synthetic paste", "exact preview uses hostile sample in settings later; panel preview allowed under queue capability"],
                ),
                "fail": "Marking done before pasteboard success is forbidden.",
                "cross": "Prompt-block delimits untrusted context. No HTML fetch.",
                "verify": ["cargo test -p bronze-domain formatters", "cargo test -p bronze-desktop copy"],
                "evidence": "golden tests",
                "nongoals": "auto-paste",
            },
            {
                "m": 5,
                "title": "Local search UI",
                "role": "user",
                "want": "to search items locally",
                "so": "I can find parked text",
                "reqs": "QUE-007, A11Y-002",
                "adrs": "ADR-018 Proposed",
                "deps": "Stories 4.7 and 6.3",
                "ac": gwt(
                    "library exists",
                    "search UI is added",
                    "results announce count without putting query in diagnostics",
                    ["QUE-007 locale tokenizer remains partial until ADR-018"],
                ),
                "fail": "Do not claim G-06 search complete.",
                "cross": "Query stays on device.",
                "verify": ["pnpm --filter desktop test -- search"],
                "evidence": "component tests",
                "nongoals": "final FTS semantics",
            },
        ],
    },
    {
        "n": 7,
        "title": "Settings shortcuts and portability UI",
        "goal": "Searchable settings, shortcut registration, permission health, backup/export UI, and i18n completion.",
        "stories": [
            {
                "m": 1,
                "title": "Settings window schema",
                "role": "user",
                "want": "searchable grouped settings with per-field reset",
                "so": "I can change behavior safely",
                "reqs": "SET-001, WIN-005",
                "adrs": "ADR-016",
                "deps": "Stories 1.7 and 5.2",
                "ac": gwt(
                    "settings capability exists",
                    "settings window is implemented",
                    "schema matches docs/12 including ShortcutActionId and daily|weekly backup",
                    ["export preview flags sensitive literals", "no credentials/tokens/paths exported"],
                ),
                "fail": "Saving invalid shortcut without rollback fails.",
                "cross": "Keyboard accessible. Catalog strings.",
                "verify": ["pnpm --filter desktop test -- settings", "cargo test -p bronze-settings"],
                "evidence": "component/unit",
                "nongoals": "shortcut recorder (next)",
            },
            {
                "m": 2,
                "title": "Shortcut recorder and registry",
                "role": "user",
                "want": "to bind every ShortcutActionId without losing the old chord on failure",
                "so": "triggers are configurable",
                "reqs": "SET-002, CAP-001, CAP-002, I18N-004, A11Y-001",
                "adrs": "ADR-016, ADR-005",
                "deps": "Story 7.1",
                "ac": gwt(
                    "settings exist",
                    "recorder is implemented",
                    "all registry actions persist in shortcuts table",
                    ["standardChord is capture.selection view only", "cannot disable chord+menu+manual together", "IME/VO chords not swallowed"],
                ),
                "fail": "Failed registration retains old binding.",
                "cross": "Spoken names localized. Test mode skippable.",
                "verify": ["cargo test -p bronze-settings shortcuts", "pnpm --filter desktop test -- shortcuts"],
                "evidence": "unit; layout matrix human",
                "nongoals": "claiming conflict-free globally",
            },
            {
                "m": 3,
                "title": "Permission health center",
                "role": "user",
                "want": "distinct permission rows with why, retest, and alternatives",
                "so": "denial is recoverable",
                "reqs": "SET-003, SET-004, CAP-003",
                "adrs": "ADR-005",
                "deps": "Stories 3.1 and 7.1",
                "ac": gwt(
                    "permission enum exists",
                    "health UI is implemented",
                    "each capability is independent",
                    ["Screen Recording shown as Not used", "denial leaves manual composer"],
                ),
                "fail": "Launch-loop prompting forbidden.",
                "cross": "No content in self-test.",
                "verify": ["pnpm --filter desktop test -- permissions"],
                "evidence": "component tests; real TCC human",
                "nongoals": "completing Story 3.9",
            },
            {
                "m": 4,
                "title": "Backup export import UI",
                "role": "user",
                "want": "Back Up Now, restore preview, and export/import flows",
                "so": "data is portable",
                "reqs": "DAT-002, DAT-003, SET-001, QUE-008",
                "adrs": "ADR-008",
                "deps": "Stories 4.5, 4.6, 6.3",
                "ac": gwt(
                    "storage APIs exist",
                    "library/settings UI calls them",
                    "native picker is Rust-owned",
                    ["automatic schedule cannot be off", "secret-content warning on queue export"],
                ),
                "fail": "WebView path strings rejected.",
                "cross": "Capability split library vs settings.",
                "verify": ["pnpm --filter desktop test -- portability", "cargo test -p bronze-desktop portability"],
                "evidence": "E2E mocked picker",
                "nongoals": "cloud backup",
            },
            {
                "m": 5,
                "title": "Native and WebView catalog parity",
                "role": "developer",
                "want": "native menu/InfoPlist strings in the same glossary",
                "so": "i18n is complete for advertised locales",
                "reqs": "I18N-001, I18N-002, I18N-003, I18N-004, G-06",
                "adrs": "ADR-014",
                "deps": "Stories 1.6, 5.1, 7.1",
                "ac": gwt(
                    "catalogs exist",
                    "native strings are extracted",
                    "en, en-XA, ar-XB cover WebView and native",
                    ["RTL smoke for panel chrome", "per-item lang/dir on cards"],
                ),
                "fail": "Hard-coded user prose fails CI.",
                "cross": "Pseudo-locales required. Human linguistic QA remains blocked.",
                "verify": ["pnpm --filter @bronze/i18n validate", "pnpm --filter desktop test -- i18n"],
                "evidence": "CI; Arabic/Japanese human later",
                "nongoals": "shipping advertised human locales without QA",
            },
        ],
    },
    {
        "n": 8,
        "title": "Visual refinement",
        "goal": "Bronze visual identity without cloning Copper, still meeting contrast and reflow.",
        "stories": [
            {
                "m": 1,
                "title": "Tokenized bronze identity",
                "role": "user",
                "want": "warm bronze accents with measured contrast",
                "so": "the app looks like Bronze",
                "reqs": "A11Y-003",
                "adrs": "ADR-012",
                "deps": "Stories 1.7 and 6.2",
                "ac": gwt(
                    "UI primitives exist",
                    "tokens from DESIGN.md are applied",
                    "normal text contrast ≥4.5:1 in light/dark in automated sampling",
                    ["concept PNG is inspiration not pixel spec", "no Copper trade dress"],
                ),
                "fail": "Color-only status fails.",
                "cross": "Increase Contrast / Differentiate Without Color variants.",
                "verify": ["pnpm --filter @bronze/ui test -- contrast"],
                "evidence": "token tests; not a public AA claim",
                "nongoals": "marketing site",
            },
            {
                "m": 2,
                "title": "Reflow two hundred and four hundred",
                "role": "user",
                "want": "200% text resize and 400%/320 CSS px reflow",
                "so": "A11Y-003 is evidenced in WebView",
                "reqs": "A11Y-003",
                "adrs": "ADR-013",
                "deps": "Stories 6.2, 6.3, 7.1",
                "ac": gwt(
                    "core screens exist",
                    "layout tests run at 320 CSS px and 200% text",
                    "no control requires two-axis scroll",
                    ["toolbar overflow labeled", "composer reachable"],
                ),
                "fail": "Lost functionality fails.",
                "cross": "en-XA long strings included.",
                "verify": ["pnpm --filter desktop test -- reflow"],
                "evidence": "layout tests; manual zoom human",
                "nongoals": "WCAG conformance claim",
            },
        ],
    },
    {
        "n": 9,
        "title": "Packaging and release evidence",
        "goal": "Reproducible packaging, SBOM, checksums, and an explicit human-validation backlog. No notarization by the agent.",
        "stories": [
            {
                "m": 1,
                "title": "Reproducible debug packaging",
                "role": "developer",
                "want": "a documented local package command with checksums",
                "so": "builds are repeatable",
                "reqs": "SEC-005",
                "adrs": "ADR-011, ADR-002 Proposed",
                "deps": "Story 1.8",
                "ac": gwt(
                    "verify passes",
                    "packaging script is added",
                    "it records arch as arm64 unless DG-01 says otherwise",
                    ["SBOM generation stub or cargo/pnpm list captured", "no get-task-allow in release config"],
                ),
                "fail": "Do not notarize or use Apple Developer credentials.",
                "cross": "No network updater.",
                "verify": ["pnpm verify", "test -f tooling/package-debug.sh"],
                "evidence": "local script output",
                "nongoals": "notarization, Developer ID, universal2",
            },
            {
                "m": 2,
                "title": "Help diagnostics and known limitations",
                "role": "user",
                "want": "local help and redacted diagnostics preview",
                "so": "support is possible offline",
                "reqs": "SUP-001, SUP-002, SEC-006",
                "adrs": "ADR-015, ADR-017",
                "deps": "Stories 3.8 and 7.1",
                "ac": gwt(
                    "settings exist",
                    "help/about/diagnostics are implemented",
                    "support bundle is previewed before export",
                    ["no automatic upload", "known limitations include human gates"],
                ),
                "fail": "Secret in bundle fails.",
                "cross": "Accessible HTML help, not image-only.",
                "verify": ["pnpm --filter desktop test -- support", "cargo test -p bronze-diagnostics bundle"],
                "evidence": "unit/component",
                "nongoals": "public ACR",
            },
            {
                "m": 3,
                "title": "Human validation backlog",
                "role": "operator",
                "want": "an explicit backlog of human-only evidence",
                "so": "the app is never called fully accessible or notarized by agents",
                "reqs": "G-04, A11Y-005, SEC-005, DG-08",
                "adrs": "ADR-013, ADR-011",
                "deps": "Stories 3.9, 3.10, 5.5",
                "ac": gwt(
                    "implementation stories exist",
                    "docs/evidence/HUMAN-GATES.md lists VoiceOver, Voice Control, Switch Control, FKA, Sticky/Slow Keys, TCC, AX matrix, IME/Arabic/Japanese, signing/notarization, independent audit",
                    "each row is pending unless a human filled it",
                    ["no story in this list is agent-done"],
                ),
                "fail": "Fabrication is forbidden.",
                "cross": "n/a",
                "verify": ["test -f docs/evidence/HUMAN-GATES.md"],
                "evidence": HUMAN,
                "nongoals": "closing DG-08",
                "human": True,
            },
        ],
    },
]


def emit() -> None:
    PLAN.mkdir(parents=True, exist_ok=True)
    IMPL.mkdir(parents=True, exist_ok=True)
    frs = [
        "G-01–G-07",
        "CAP-001–CAP-010",
        "QUE-001–QUE-008",
        "WIN-001–WIN-005",
        "DAT-001–DAT-004",
        "SEC-001–SEC-006",
        "A11Y-001–A11Y-006",
        "I18N-001–I18N-004",
        "SET-001–SET-004",
        "SUP-001–SUP-002",
    ]
    lines = [
        "---",
        "stepsCompleted: [1, 2, 3, 4]",
        "inputDocuments:",
        "  - docs/03-prd.md",
        "  - docs/05-ux-ui-interaction-spec.md",
        "  - docs/06-system-architecture.md",
        "  - docs/18-adrs.md",
        "  - docs/14-agentic-implementation-plan.md",
        "  - docs/21-preimplementation-reconciliation.md",
        "  - _bmad-output/planning-artifacts/prds/prd-bronze-app-2026-08-27/prd.md",
        "  - _bmad-output/planning-artifacts/ux-designs/ux-bronze-app-2026-08-27/DESIGN.md",
        "  - _bmad-output/planning-artifacts/ux-designs/ux-bronze-app-2026-08-27/EXPERIENCE.md",
        "  - _bmad-output/planning-artifacts/architecture/architecture-bronze-app-2026-08-27/ARCHITECTURE-SPINE.md",
        "---",
        "",
        "# bronze-app - Epic Breakdown",
        "",
        "## Overview",
        "",
        "Bronze v1 macOS selection-to-action queue. Stories are sized for one fresh agent context. Risk (toolchain, native bridge, capture, store) precedes polish. Human-only evidence stories stay `blocked-human-validation`.",
        "",
        "## Requirements Inventory",
        "",
        "### Functional Requirements",
        "",
    ]
    lines += [f"- {x}" for x in frs]
    lines += [
        "",
        "### NonFunctional Requirements",
        "",
        "- Local-only default; no telemetry/account/network (G-05, SEC-004, ADR-017)",
        "- WCAG 2.2 AA WebView evidence without public conformance claim (G-04, ADR-013)",
        "- BCP 47 / ICU / RTL / IME (G-06, ADR-014)",
        "- Capture reliability G-01/G-02",
        "",
        "### Additional Requirements",
        "",
        "- Phase 4 UI/i18n/capture guardrails in the autonomous delivery prompt",
        "- docs/21 closed enums",
        "",
        "### UX Design Requirements",
        "",
        "- Immediate persist; physical panel edge; semantic HTML; 200%/400%/320; native display prefs",
        "",
        "### FR Coverage Map",
        "",
        "| IDs | Epic |",
        "| --- | --- |",
        "| SEC-001–004, I18N-001–002, A11Y-001–003 slots | Epic 1 |",
        "| CAP-004, ADR-004 | Epic 2 |",
        "| CAP-001–010, SET-003 | Epic 3 |",
        "| DAT-001–004, QUE-001–007 domain | Epic 4 |",
        "| WIN-001–005, A11Y-003 display | Epic 5 |",
        "| QUE-001–008 UI, QUE-004–005 | Epic 6 |",
        "| SET-001–004, DAT-002–003 UI, I18N-001–004 | Epic 7 |",
        "| A11Y-003 visual | Epic 8 |",
        "| SEC-005–006, SUP-001–002, G-04 human | Epic 9 |",
        "",
        "## Epic List",
        "",
    ]
    for epic in EPICS:
        lines.append(f"{epic['n']}. Epic {epic['n']}: {epic['title']}")
    lines.append("")

    story_files: list[tuple[str, str, bool, int, int, str]] = []
    for epic in EPICS:
        lines.append(f"## Epic {epic['n']}: {epic['title']}")
        lines.append("")
        lines.append(epic["goal"])
        lines.append("")
        for st in epic["stories"]:
            human = bool(st.get("human"))
            body = story_md(
                st["title"],
                st["role"],
                st["want"],
                st["so"],
                st["reqs"],
                st["adrs"],
                st["deps"],
                st["ac"],
                st["fail"],
                st["cross"],
                st["verify"],
                st["evidence"],
                st["nongoals"],
                human=human,
            )
            lines.append(f"### Story {epic['n']}.{st['m']}: {st['title']}")
            lines.append("")
            lines.append(body)
            lines.append("")
            slug = "".join(ch.lower() if ch.isalnum() else "-" for ch in st["title"]).strip("-")
            while "--" in slug:
                slug = slug.replace("--", "-")
            key = f"{epic['n']}-{st['m']}-{slug}"
            story_files.append((key, st["title"], human, epic["n"], st["m"], body))

    (PLAN / "epics.md").write_text("\n".join(lines) + "\n")
    for key, title, human, en, sm, body in story_files:
        status = "blocked-human-validation" if human else "ready-for-dev"
        text = f"""# Story {en}.{sm}: {title}

Status: {status}

## Story

{body}

## Dev Agent Record

### Agent Model Used

### File List
"""
        (IMPL / f"{key}.md").write_text(text)
    print(f"wrote epics.md and {len(story_files)} story files")


if __name__ == "__main__":
    emit()
